package common

const (
	ID_GENERATOR_MACHINE_ID = 911
	DEFAULT_WALLET_EXT_INFO = "This is wallet detail info"

	MONEY_ACTION_TYPE_MONEY_IN  = 0
	MONEY_ACTION_TYPE_MONEY_OUT = 1

	ORDER_TYPE_DEPOSIT  = 0
	ORDER_TYPE_WITHDRAW = 1
	ORDER_TYPE_TRANSFER = 3

	MONEY_ACTION_SERVICE_INIT_OPTION_DB_TRANSACTION = 0
	MONEY_ACTION_SERVICE_INIT_OPTION_TCC            = 1
	MONEY_ACTION_SERVICE_INIT_OPTION_ASYNC          = 2

	TRANSACTION_STATUS_PENDING  = 0
	TRANSACTION_STATUS_COMPLETE = 1
	TRANSACTION_STATUS_FAILED   = 2
	TRANSACTION_STATUS_CANCELED = 3
)
